---
- name : configure rsyslog
  hosts : media
  become: true
  gather_facts: false

  tasks :
    - name : install pkg && update cache
      ansible.builtin.apt:
        name : rsyslog
        update_cache: true

    - name : enable service
      ansible.builtin.service:
        name : rsyslog
        state: started
        enabled: true

    - name : template
      ansible.builtin.template:
        src: 10-samba.conf.j2
        dest: /etc/rsyslog.d/10-samba.conf
        owner: root
        group : root
        mode: '0644'
      notify: 
        - restart rsyslogd

  handlers:
    - name : restart rsyslogd
      ansible.builtin.service:
        name : rsyslog
        state: restarted
      
    


